- hosts: localhost
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        update_cache: true
      tags:
      - core
      - zsh
      - node
  tasks:
  - include: tasks/core.yml
  - include: tasks/zsh.yml
  - include: tasks/dotfiles.yml
  - include: tasks/nvim.yml
  - include: tasks/node.yml
  - include: tasks/dotnet.yml
