- name: Install docker prerequisites
  become: true
  apt:
    update_cache: yes
    pkg:
    - ca-certificates
    - curl
    - gnupg
  tags:
  - docker

- name: Create keyrings directory
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
  - docker

- name: Download and dearmor docker GPG key
  become: true
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  tags:
  - docker

- name: Make docker GPG key readable by all
  become: true
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: a+r
  tags:
  - docker

- name: Setup repository
  become: true
  shell: |
    echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null
  tags:
  - docker

- name: Install docker packages
  become: true
  apt:
    update_cache: yes
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  tags:
  - docker

- name: Add current user to docker group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  tags:
  - docker
