- name: Clone dotfiles
  git:
    repo: "https://github.com/blalockma/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
  tags:
  - dotfiles

- name: Remove old .zshrc
  file:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: absent
  tags:
  - dotfiles

- name: Symlink all dotfiles
  shell: "./setup-env.sh"
  args:
    executable: /bin/bash
    chdir: "{{ lookup('env', 'HOME') }}/dotfiles/"
  tags:
  - dotfiles
