- name: Github global user name
  git_config:
    name: user.name
    scope: global
    value: "Mason Blalock"
  tags:
  - git
- name: Github global user email
  git_config:
    name: user.email
    scope: global
    value: "15042748+blalockma@users.noreply.github.com"
  tags:
  - git
- name: Download lazygit
  become: true
  shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep '"tag_name":' |  sed -E 's/.*"v*([^"]+)".*/\1/')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
  tags:
  - git
- name: Install lazygit
  become: true
  shell: tar xf lazygit.tar.gz -C /usr/local/bin lazygit
  tags:
  - git
- name: Cleanup lazygit
  become: true
  shell: rm lazygit.tar.gz
  tags:
  - git
