- name: Install node
  apt:
    name: ['nodejs', 'npm']
  tags:
  - node
- name: Install node manager
  npm:
    name: n
    global: true
  tags:
  - node
- name: Install node version 20
  shell: n 20
  tags:
  - node
