- name: Add neovim repo
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/unstable
  tags:
  - nvim
- name: Install neovim
  become: true
  apt:
    name: neovim
    update_cache: yes
  tags:
  - nvim
- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
  - nvim
