- name: Download neovim
  become: true
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.9.0/nvim.appimage
    dest: /usr/bin/nvim
    mode: '0755'
  tags:
  - nvim
- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
  - nvim
