- name: Install zsh
  become: true
  apt: name=zsh
  tags:
  - zsh
- name: Change shell
  become: true
  shell: "chsh -s `which zsh` mason"
  tags:
  - zsh
- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
  - zsh
